# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e274634e465eb105e957eed8a6f420caf8ddce57bd69b31fda5f59321e85d4726b32e56835db076f4daa2dae7ed9747cb83862026f1f71d5ad39a40ae1e2dc

test:
  secret_key_base: 3013b20cc701410861c5557f3c0c60d09ee41ab50575130820fa0e0c17fc4775d7ee42c6a7c08492402db322ae60106d1f0f6c120220278444f5f74f7d276b9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
